#!/bin/sh

# IPv6 Relay Mode Configuration Script
# This script runs once during package installation

. /lib/functions.sh

# Check if already configured
[ "$(uci -q get dhcp.lan.ra)" = "relay" ] && {
	echo "IPv6 relay already configured"
	exit 0
}

echo "Configuring IPv6 relay mode..."

# Configure LAN interface for IPv6 relay
uci -q batch <<-EOF
	set dhcp.lan.ra='relay'
	set dhcp.lan.dhcpv6='relay'
	set dhcp.lan.ndp='relay'
	set dhcp.lan.ndproxy_routing='0'
	delete dhcp.lan.ra_flags
	add_list dhcp.lan.ra_flags='none'
EOF

# Check if WAN6 interface exists in network config
if ! uci -q get network.wan6 >/dev/null; then
	echo "Creating WAN6 interface..."
	uci -q batch <<-EOF
		set network.wan6='interface'
		set network.wan6.proto='dhcpv6'
		set network.wan6.device='@wan'
		set network.wan6.reqaddress='try'
		set network.wan6.reqprefix='auto'
		set network.wan6.sourcefilter='0'
	EOF
fi

# Configure WAN6 DHCP settings
uci -q batch <<-EOF
	set dhcp.wan6='dhcp'
	set dhcp.wan6.interface='wan6'
	set dhcp.wan6.ignore='1'
	set dhcp.wan6.ra='relay'
	set dhcp.wan6.dhcpv6='relay'
	set dhcp.wan6.ndp='relay'
	set dhcp.wan6.master='1'
	set dhcp.wan6.ndproxy_routing='0'
	delete dhcp.wan6.ra_flags
	add_list dhcp.wan6.ra_flags='none'
EOF

# Disable IPv6 ULA prefix (optional)
uci -q delete network.globals.ula_prefix

# Configure odhcpd settings
uci -q batch <<-EOF
	set dhcp.odhcpd.maindhcp='0'
	set dhcp.odhcpd.leasefile='/tmp/hosts/odhcpd'
	set dhcp.odhcpd.leasetrigger='/usr/sbin/odhcpd-update'
	set dhcp.odhcpd.loglevel='4'
EOF

# Commit all changes
uci commit dhcp
uci commit network

# Enable the service
/etc/init.d/ipv6-relay-fix enable

echo "IPv6 relay mode configured successfully"
exit 0
